ALTER TABLE Turfs ADD COLUMN Description TEXT DEFAULT NULL;
ALTER TABLE Turfs ADD COLUMN ImageURL VARCHAR(500) DEFAULT NULL;
ALTER TABLE Turfs ADD COLUMN Location VARCHAR(255) DEFAULT NULL;
ALTER TABLE Turfs ADD COLUMN WeekendPriceMultiplier DECIMAL(3,2) DEFAULT 1.00;
ALTER TABLE Turfs ADD COLUMN MaintenanceLockStart DATE DEFAULT NULL;
ALTER TABLE Turfs ADD COLUMN MaintenanceLockEnd DATE DEFAULT NULL;
ALTER TABLE Turfs ADD COLUMN CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
