ALTER TABLE Users ADD COLUMN Status VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE Users ADD COLUMN AvatarURL VARCHAR(500) DEFAULT NULL;
ALTER TABLE Users ADD COLUMN CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
